"""Application business services."""

from app.services.address_engine import (
    ParsedAddress,
    check_contradiction,
    confirm_address_and_save,
    format_address_dry_run_summary,
    get_parser,
    get_saved_address_choice_message,
    handle_address_edit,
    handle_use_saved_address,
    parse_raw_address,
    process_address_input,
    resolve_address_contradiction,
    set_parser,
)
from app.services.address_session import (
    AddressSession,
    clear_address_session,
    clear_all_address_sessions,
    create_or_get_address_session,
    get_address_session,
    reset_address_session_for_edit,
    update_address_session,
)
from app.services.escalation_service import (
    EscalationError,
    InvalidApprovalStateError,
    approve_manual,
    check_escalation_tier,
    escalate_for_manual_review,
    reject_manual,
    release_stale_claims,
)
from app.services.escalation_service import (
    OrderNotFoundError as EscalationOrderNotFoundError,
)
from app.services.flex_builder import build_product_carousel, build_product_flex_message
from app.services.fulfillment_service import (
    FulfillmentError,
    InvalidOrderStateForFulfillmentError,
    fulfill_order,
    fulfill_order_with_retry,
)
from app.services.fulfillment_service import (
    OrderNotFoundError as FulfillmentOrderNotFoundError,
)
from app.services.gateway_webhook_service import (
    GatewayWebhookError,
    InvalidSignatureError,
    MalformedPayloadError,
    compute_gateway_signature,
    process_gateway_webhook,
    verify_gateway_signature,
)
from app.services.i18n import get_text, resolve_user_language, set_user_language
from app.services.intent_router import dispatch_event
from app.services.order_service import (
    EmptyCartError,
    InvalidQuantityError,
    OutOfStockError,
    ProductNotFoundError,
    add_item_to_draft,
    confirm_draft_order,
    format_order_summary,
    get_active_draft_order,
    get_or_create_draft_order,
    get_order_by_id,
    list_orders,
    product_has_sizes,
)
from app.services.sheet_ingest import SheetsAPIError
from app.services.verification_log_service import log_verification
from app.services.verification_service import (
    VerificationResult,
    build_test_slip_qr,
    claim_payment,
    compute_crc16_ccitt_false,
    parse_tlv,
    verify_slip_local,
)

__all__ = [
    "AddressSession",
    "ParsedAddress",
    "check_contradiction",
    "clear_address_session",
    "clear_all_address_sessions",
    "confirm_address_and_save",
    "create_or_get_address_session",
    "format_address_dry_run_summary",
    "get_address_session",
    "get_parser",
    "get_saved_address_choice_message",
    "handle_address_edit",
    "handle_use_saved_address",
    "parse_raw_address",
    "process_address_input",
    "reset_address_session_for_edit",
    "resolve_address_contradiction",
    "set_parser",
    "update_address_session",
    "get_text",
    "resolve_user_language",
    "set_user_language",
    "build_rich_menu_object",
    "create_and_link_rich_menu",
    "build_product_carousel",
    "build_product_flex_message",
    "dispatch_event",
    "EmptyCartError",
    "InvalidQuantityError",
    "OutOfStockError",
    "ProductNotFoundError",
    "add_item_to_draft",
    "confirm_draft_order",
    "format_order_summary",
    "get_active_draft_order",
    "get_or_create_draft_order",
    "get_order_by_id",
    "list_orders",
    "product_has_sizes",
    "EscalationError",
    "InvalidApprovalStateError",
    "EscalationOrderNotFoundError",
    "approve_manual",
    "check_escalation_tier",
    "escalate_for_manual_review",
    "reject_manual",
    "release_stale_claims",
    "log_verification",
    "VerificationResult",
    "build_test_slip_qr",
    "claim_payment",
    "compute_crc16_ccitt_false",
    "parse_tlv",
    "verify_slip_local",
    "compute_gateway_signature",
    "verify_gateway_signature",
    "process_gateway_webhook",
    "GatewayWebhookError",
    "InvalidSignatureError",
    "MalformedPayloadError",
    "FulfillmentError",
    "FulfillmentOrderNotFoundError",
    "InvalidOrderStateForFulfillmentError",
    "fulfill_order",
    "fulfill_order_with_retry",
    "SheetsAPIError",
]
